language: node_js
node_js:
  - '10'

before_install:
  - npm install -g greenkeeper-lockfile
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

install:
  - npm install
  - npm build
script:
  - npm run test_with_push

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
